name: Cypress Tests

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the workflow every 5 minutes
  push:
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
